version: "3.8"

services:
  server:
    image: node:12-alpine
    container_name: server
    command:
      sh -c "bin/start.sh" 
    working_dir: /xsky-oem-platform
    ports:
      - 3000:3000
    volumes:
      - ./packages:/xsky-oem-platform
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: secret
      KEYMETRICS_PUBLIC: mizxmb1hmddbzcd
      KEYMETRICS_SECRET: c5n3t93ausiexri
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    container_name: pgsql
    privileged: true  
    volumes:
      - ome-postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: secret

  nginx:
    image: nginx:alpine
    restart: always
    container_name: nginx
    ports:
      - 8056:80
    volumes:
      - ./packages/server/build:/xsky-oem-platform/server/build
      - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server

volumes:
  ome-postgres-data:
